export const enum SocketOMessage {
    ROTATED_SIMULATION = 'ROTATED_SIMULATION',
    CHANGED_SIMULATION = 'CHANGED_SIMULATION',
    CHANGED_AUTOPLAY_SIMULATION = 'CHANGED_AUTOPLAY_SIMULATION',
    MESSAGE = 'MESSAGE',
    JOINED_ROOM = 'JOINED_ROOM',
    LEFT_ROOM = 'LEFT_ROOM',
    SESSION_LIST_REFRESH = 'SESSION_LIST_REFRESH'
}

export const enum SocketIMessage {
    SEND_MESSAGE = 'SEND_MESSAGE',
    ROTATE_SIMULATION = 'ROTATE_SIMULATION',
    CHANGE_SIMULATION = 'CHANGE_SIMULATION',
    CHANGE_AUTOPLAY_SIMULATION = 'CHANGE_AUTOPLAY_SIMULATION',
    JOIN_ROOM = 'JOIN_ROOM',
    LEAVE_ROOM = 'LEAVE_ROOM'
}
